"use client";
import { useEffect,useMemo,useState } from "react";
import { MessageSquare, RefreshCw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
export default function AdminFeedback(){
 const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [loading,setLoading]=useState(true);const [note,setNote]=useState("");const [status,setStatus]=useState("reviewed");
 async function token(){const {data:{session}}=await supabase.auth.getSession();return session?.access_token||""}
 async function load(){setLoading(true);const t=await token();const r=await fetch("/api/admin/feedback",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(r.ok)setItems(j.items||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 function open(x:any){setSelected(x);setNote(x.admin_note||"");setStatus(x.status||"reviewed")}
 async function save(){if(!selected)return;const t=await token();await fetch("/api/admin/feedback",{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,status,admin_note:note})});await load();setSelected(null)}
 if(loading)return <div className="py-16 text-center text-sm text-white/35">Chargement feedback…</div>;
 return <div className="space-y-4 pb-10"><div className="flex items-end justify-between"><div><div className="text-[9px] uppercase text-[color:var(--gold)]">Voix utilisateurs</div><h1 className="mt-2 text-2xl font-semibold text-white">Feedback <span className="text-[color:var(--gold)]">bêta</span></h1></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[color:var(--gold-border)] bg-[color:var(--gold-soft)] px-4 text-xs text-[color:var(--gold)]"><RefreshCw size={13}/>Actualiser</button></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_1fr]"><section className="rounded-2xl border border-white/[.07] bg-white/[.02] divide-y divide-white/[.05]">{items.length?items.map(x=><button key={x.id} onClick={()=>open(x)} className="w-full p-4 text-left hover:bg-white/[.02]"><div className="flex items-center justify-between gap-3"><div className="text-xs font-semibold text-white">{x.member?.username||"Membre"} · {x.category}</div><span className="text-[8px] text-[color:var(--gold)]">{x.rating?`${x.rating}/5`:"—"}</span></div><p className="mt-2 line-clamp-2 text-[10px] text-white/35">{x.message}</p><div className="mt-2 text-[8px] text-white/20">{x.status} · {new Date(x.created_at).toLocaleString("fr-FR")}</div></button>):<div className="p-12 text-center text-xs text-white/25">Aucun feedback.</div>}</section><section className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4">{selected?<><div className="text-sm font-semibold text-white">{selected.member?.username||"Membre"}</div><div className="mt-1 text-[9px] text-white/30">{selected.category} · {selected.page_path||"—"}</div><div className="mt-4 rounded-xl border border-white/[.06] bg-black/20 p-4 text-[11px] leading-5 text-white/55 whitespace-pre-wrap">{selected.message}</div><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-4 h-10 w-full rounded-xl border border-white/[.08] bg-black/30 px-3 text-xs text-white"><option value="new">new</option><option value="reviewed">reviewed</option><option value="resolved">resolved</option><option value="closed">closed</option></select><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Note interne" className="mt-3 w-full rounded-xl border border-white/[.08] bg-black/30 p-3 text-xs text-white"/><button onClick={()=>void save()} className="mt-3 h-10 w-full rounded-xl bg-[color:var(--gold)] text-xs font-semibold text-black">Enregistrer</button></>:<div className="grid min-h-[360px] place-items-center text-center text-xs text-white/25"><div><MessageSquare className="mx-auto mb-3"/>Sélectionne un retour.</div></div>}</section></div></div>
}
