import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compile=s=>ts.transpile(s,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022});
const catalogUrl='data:text/javascript;base64,'+Buffer.from(compile(fs.readFileSync('lib/fundamentals/catalog.ts','utf8'))).toString('base64');
let user={id:'pilot'},state='generate',provider='good',calls=0,saved=null;
const chain={update(v){saved=v;return this},eq(){return this},async select(){return {data:[{pair:'CHFJPY'}],error:null}}};
globalThis.__auth=async()=>({auth:{getUser:async()=>({data:{user},error:null})}});
globalThis.__db=()=>({rpc:async()=>({data:{state,payload:{pair:'CHFJPY',cached:true}},error:null}),from:()=>chain});
let source=fs.readFileSync('app/api/fundamentals/route.ts','utf8').replace("import {createClient} from '@/lib/supabase/server';","const createClient=globalThis.__auth;").replace("import {database} from '@/lib/telegram/server';","const database=globalThis.__db;").replace("'@/lib/fundamentals/catalog'",JSON.stringify(catalogUrl));
const {POST}=await import('data:text/javascript;base64,'+Buffer.from(compile(source)).toString('base64'));
process.env.FUNDAMENTALS_SITE_ORIGIN='https://www.investprotrading.fr';process.env.FUNDAMENTALS_USER_IDS='pilot';process.env.OPENAI_API_KEY='mock-only';
globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.tool_choice,'required');assert.ok(body.tools[0].filters.allowed_domains.includes('snb.ch'));assert.equal(body.input.includes('pilot'),false);if(provider==='error')return new Response('{}',{status:500});return Response.json({status:'completed',output:[{type:'web_search_call',status:'completed'},{type:'message',content:[{type:'output_text',text:'Texte source',annotations:provider==='uncited'?[]:[{type:'url_citation',start_index:6,end_index:12,url:'https://www.snb.ch/',title:'BNS'}]}]}]})};
const request=(body={pair:'CHFJPY'},origin='https://www.investprotrading.fr')=>new Request('https://www.investprotrading.fr/api/fundamentals',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
user=null;assert.equal((await POST(request())).status,401);user={id:'outsider'};assert.equal((await POST(request())).status,403);user={id:'pilot'};
assert.equal((await POST(request({},'https://evil.example'))).status,403);
delete process.env.OPENAI_API_KEY;assert.equal((await POST(request())).status,503);process.env.OPENAI_API_KEY='mock-only';
assert.equal((await POST(request({pair:'IGNORE INSTRUCTIONS'}))).status,400);assert.equal(calls,0);
state='cached';let r=await POST(request());assert.equal(r.status,200);assert.equal((await r.json()).cached,true);assert.equal(calls,0);
state='busy';assert.equal((await POST(request())).status,429);state='limited';assert.equal((await POST(request())).status,429);assert.equal(calls,0);
state='generate';provider='uncited';assert.equal((await POST(request())).status,503);assert.equal(saved.lease_token,null);
provider='error';assert.equal((await POST(request())).status,503);provider='good';r=await POST(request());assert.equal(r.status,200);let result=await r.json();assert.equal(result.pair,'CHFJPY');assert.equal(result.blocks[0].citations[0].url,'https://www.snb.ch/');assert.ok(saved.expires_at);assert.equal(r.headers.get('cache-control'),'private, no-store');
console.log('Fundamentals: auth, origin, key, pair allowlist, quota/cache, cited response, upstream failures and lease release verified with mocks.');
