import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const js=ts.transpile(fs.readFileSync('lib/sth/client.ts','utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022});
const {partnerCall,lotValue}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
process.env.STH_PARTNER_LICENSE='test-secret';process.env.STH_MAX_LOTS='0.10';
let body;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://socialtradehubapp.com/Partner/get-user-status');body=JSON.parse(options.body);return Response.json({isTradingAccountConnected:true,masterAccountsList:[{id:'A',name:'Master',userIsSubscribed:true,lots:0.01}],errorMessage:''});};
const s=await partnerCall('get-user-status','verified-user',{UserID:'forged',PartnerLicense:'forged'});assert.equal(body.UserID,'verified-user');assert.equal(body.PartnerLicense,'test-secret');assert.equal(s.masterAccountsList[0].lots,0.01);assert.equal('PartnerLicense' in s,false);
globalThis.fetch=async()=>Response.json({errorMessage:'Invalid Partner License test-secret'});await assert.rejects(()=>partnerCall('get-user-status','u'),/^Error: LICENCE$/);
globalThis.fetch=async()=>Response.json({errorMessage:'Service is busy...'});await assert.rejects(()=>partnerCall('get-user-status','u'),/^Error: BUSY$/);
globalThis.fetch=async()=>{throw Error('secret')};await assert.rejects(()=>partnerCall('get-user-status','u'),/^Error: UNKNOWN_RESULT$/);
globalThis.fetch=async()=>Response.json({status:'processing'});await assert.rejects(()=>partnerCall('get-user-status','u'),/^Error: UNKNOWN_RESULT$/);
assert.equal(lotValue('0.01'),0.01);for(const v of [0,-1,1,'bad',Infinity])assert.throws(()=>lotValue(v));console.log('STH : contrat de statut, erreurs HTTP 200, secrets masqués, identité serveur, timeouts et limites de lots vérifiés. Aucun appel réel.');
let calls=0;
globalThis.__sthTest={createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'pilot-user'}}})}}),databaseClient:()=>{throw Error('Unexpected database call');},partnerCall:async()=>{calls++;return s;},lotValue};
let route=ts.transpile(fs.readFileSync('app/api/sth/route.ts','utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022});
route=route.replace(/import .* from ['"]@\/lib\/supabase\/server['"];?/, 'const {createClient}=globalThis.__sthTest;').replace(/import .* from ['"]@supabase\/supabase-js['"];?/, 'const {databaseClient}=globalThis.__sthTest;').replace(/import .* from ['"]@\/lib\/sth\/client['"];?/, 'const {partnerCall,lotValue}=globalThis.__sthTest;');
const api=await import('data:text/javascript;base64,'+Buffer.from(route).toString('base64'));
process.env.STH_ENABLED='true';process.env.STH_PILOT_USER_IDS='other';process.env.VERCEL_ENV='production';
assert.equal((await api.GET()).status,403);assert.equal(calls,0);
process.env.STH_PILOT_USER_IDS='pilot-user';process.env.VERCEL_ENV='preview';
assert.equal((await api.POST(new Request('https://site.test/api/sth',{method:'POST'}))).status,403);assert.equal(calls,0);
process.env.VERCEL_ENV='production';process.env.STH_SITE_ORIGIN='https://site.test';
assert.equal((await api.POST(new Request('https://site.test/api/sth',{method:'POST',headers:{origin:'https://evil.test'}}))).status,403);
assert.equal((await api.POST(new Request('https://site.test/api/sth',{method:'POST',headers:{origin:'https://site.test'},body:JSON.stringify({action:'disconnect',consent:false})}))).status,400);assert.equal(calls,0);
console.log('API : accès pilote, blocage Preview, origine et consentement vérifiés.');
