import ts from 'typescript';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=ts.transpile(fs.readFileSync('lib/telegram/engine.ts','utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022});
const {parseMessage,buildStats}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const signal='🎯 #SIGNAL\n🟡 Actif : GOLD\nDirection : BUY\n📍 Entrée : 4257.4 - 4252.97\nStop Loss : 4244.26\nTP1 : 4271\nTP2 : 4284\nTP3 : 4300';
const p=parseMessage(signal);assert.equal(p.kind,'signal');assert.equal(p.signal.entry,4255.1849999999995);
const ev=(id,text,reply=null)=>({message_id:id,date:1790546400+id,reply_to:reply,parsed:parseMessage(text)});
const base=ev(1,signal);let out=buildStats([base,ev(2,'TP1 TOUCHER',1),ev(3,'GOLD TP2 TOUCHER +320 PIPS',1)]);assert.equal(out.trades.length,1);assert.equal(out.trades[0].target,2);assert.ok(Math.abs(out.trades[0].r-2.6375286)<1e-5);
assert.equal(buildStats([base,ev(2,'TP3 touché',1),ev(3,'TP1 TOUCHER',1)]).trades[0].target,3);
assert.equal(buildStats([base,ev(2,'SL',1)]).trades[0].r,-1);
assert.equal(buildStats([base,ev(2,'Stop loss touché',1)]).trades[0].status,'loss');
assert.equal(buildStats([base,ev(2,'TP1 TOUCHER',1),ev(3,'TP2 TOUCHER',2)]).trades[0].target,2);
assert.equal(buildStats([base,ev(2,'TP1 TOUCHER',1),ev(3,'Stop loss touché',1)]).trades[0].status,'review');
assert.equal(buildStats([base,ev(2,'TP9 TOUCHER',1)]).trades[0].status,'review');
assert.equal(buildStats([base,ev(2,'TP1 TOUCHER')]).trades[0].status,'pending');
assert.equal(parseMessage('TP1 pas touché').kind,'review');assert.equal(parseMessage('Si TP1 touché').kind,'review');assert.equal(parseMessage('TP1 touché ?').kind,'review');
assert.equal(parseMessage('Bonjour tout le monde').kind,'ignore');assert.equal(parseMessage('ANNULÉ').kind,'ignore');
const sell=signal.replace('BUY','SELL').replace('4257.4 - 4252.97','4275 - 4276').replace('4244.26','4310').replace('4271','4270').replace('4284','4260').replace('4300','4250');assert.equal(parseMessage(sell).kind,'signal');
assert.equal(parseMessage(signal.replace('TP2 : 4284','TP2 : 4250')).kind,'review');assert.equal(parseMessage(signal.replace('TP2 : 4284','TP1 : 4284')).kind,'review');
assert.equal(parseMessage(signal.replace('TP2 : 4284','')).kind,'review');
const corrected=buildStats([base,ev(2,'ANNULÉ',1),ev(3,'Stop loss touché',1)]);assert.equal(corrected.trades[0].r,-1);
assert.equal(buildStats([ev(2,'TP2 TOUCHER',1),base]).trades[0].target,2);
assert.equal(buildStats([base,ev(2,'TP2 TOUCHER',1),ev(3,'TP2 TOUCHER',1)]).trades[0].r,out.trades[0].r);
assert.equal(buildStats([{...base,date:Date.parse('2026-09-30T22:30:00Z')/1000}]).trades[0].date,'2026-10-01');
console.log('Telegram : 23 assertions réussies (signaux, TP/SL, corrections, doublons, ordre et fuseau).');
let writes=[];
const fakeDb={rpc:async(name,args)=>{writes.push({name,args});return {error:null};}};
globalThis.__telegramTest={database:()=>fakeDb,channel:()=>'-1001234567890',parseMessage};
let route=ts.transpile(fs.readFileSync('app/api/telegram/webhook/route.ts','utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022});
route=route.replace(/import .* from ['"]@\/lib\/telegram\/server['"];?/, 'const {database,channel}=globalThis.__telegramTest;').replace(/import .* from ['"]@\/lib\/telegram\/engine['"];?/, 'const {parseMessage}=globalThis.__telegramTest;');
const {POST}=await import('data:text/javascript;base64,'+Buffer.from(route).toString('base64'));
process.env.TELEGRAM_WEBHOOK_SECRET='a'.repeat(64);
const request=(payload,secret='a'.repeat(64))=>new Request('https://example.test/api/telegram/webhook',{method:'POST',headers:{'x-telegram-bot-api-secret-token':secret},body:JSON.stringify(payload)});
const payload={update_id:1,channel_post:{message_id:1,date:1790546400,chat:{id:-1001234567890,type:'channel'},text:signal}};
assert.equal((await POST(request(payload,'wrong'))).status,401);assert.equal(writes.length,0);
assert.equal((await POST(request({...payload,channel_post:{...payload.channel_post,chat:{id:-1009999999999,type:'channel'}}}))).status,200);assert.equal(writes.length,0);
assert.equal((await POST(request(payload))).status,200);assert.equal(writes.length,1);assert.equal(writes[0].args.p_parsed.kind,'signal');
assert.equal((await POST(request({...payload,channel_post:undefined,edited_channel_post:{...payload.channel_post,edit_date:1790546500,text:signal.replace('4271','4272')}}))).status,200);assert.equal(writes[1].args.p_revision,1790546500);
fakeDb.rpc=async()=>({error:{message:'database unavailable'}});assert.equal((await POST(request(payload))).status,503);
console.log('Webhook : rejet des secrets invalides, filtrage canal, réception, édition et reprise après erreur vérifiés.');
