import Link from 'next/link';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import AuraLanding from '@/components/aura/Landing';
export default function Home(){return <div className="aura-faithful"><div className="landing">
<header className="landing-nav"><Link href="/" className="brand"><div className="brand-mark"><span/><span/><span/></div><div>investpro<span className="brand-sub">TRADING</span></div></Link><nav><a href="#pourquoi">Pourquoi InvestPro</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#beta">Accès bêta</a><a href="#faq">FAQ</a></nav><Link className="btn primary" href="/dashboard">Explorer l’espace <ArrowRight size={17}/></Link></header>
<main><AuraLanding/>
<section className="beta-section" id="beta"><div><span className="eyebrow">ACCÈS BÊTA</span><h2>Votre espace de trading.<br/><em>Gratuit pendant la bêta.</em></h2><p>Préparez vos sessions, suivez vos comptes et comprenez vos résultats dans un même espace.</p><Link className="btn primary" href="/dashboard">Découvrir mon espace <ArrowRight size={17}/></Link></div><div className="beta-card"><span className="tag gold">LES ESSENTIELS</span><h3>Une base pour progresser</h3><ul>{['Dashboard & suivi des résultats','Journal de trading','Mes comptes','Plan de trading & simulateur','Calendrier économique & analyses'].map(t=><li key={t}><CheckCircle2 size={17}/>{t}</li>)}</ul><div className="beta-next"><span>EN PRÉPARATION</span><p>Copieur · Synchronisation des comptes</p></div><p className="field-help">L’accès bêta à la plateforme est distinct de l’accès au groupe VIP.</p></div></section>
<section className="why-section" id="pourquoi"><span className="eyebrow">POURQUOI INVESTPRO</span><h2>Plus de clarté.<br/>Plus de discipline. <em>Plus de contrôle.</em></h2><div>{[['01','Une vision de vos comptes','Retrouvez votre capital et vos résultats sans disperser votre suivi.'],['02','Une méthode à respecter','Gardez vos règles de risque et votre préparation à portée de main.'],['03','Une progression à comprendre','Relisez vos opérations, documentez vos décisions et identifiez vos habitudes.']].map(([n,title,p])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{p}</p></article>)}</div></section>
<section className="landing-faq" id="faq"><div><span className="eyebrow">FOIRE AUX QUESTIONS</span><h2>Vos questions.<br/>Des réponses claires.</h2></div><div>{[
['À quoi sert le journal de trading ?','Il rassemble vos opérations, leurs résultats et vos notes pour vous aider à comprendre vos décisions.'],
['Puis-je suivre plusieurs comptes ?','Vous pouvez organiser votre suivi dans Mes comptes. La connexion automatique aux courtiers est en préparation.'],
['Le copieur est-il disponible ?','Le copieur est en développement. Son ouverture à la communauté sera annoncée après l’intégration et les tests.'],
['Comment lire les performances VIP ?','Le suivi Telegram présente les résultats théoriques des signaux reçus et des TP ou SL annoncés. Il reste distinct des gains réellement réalisés sur votre compte.'],
['Puis-je utiliser InvestPro sur mobile ?','Oui. Retrouvez votre espace depuis le navigateur de votre téléphone. Vous pouvez aussi ajouter le site à votre écran d’accueil.'],
['Les résultats sont-ils garantis ?','Non. Le trading comporte un risque de perte en capital. Les performances passées et les signaux ne garantissent aucun résultat futur.']
].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className="landing-end"><span className="eyebrow">INVESTPRO TRADING</span><h2>Le prochain trade commence<br/>par une meilleure préparation.</h2><Link className="btn primary" href="/dashboard">Ouvrir mon espace <ArrowRight size={18}/></Link></section></main>
<footer><Link href="/" className="brand">investpro<span className="brand-sub">TRADING</span></Link><p>Le trading comporte un risque de perte en capital.</p><div><Link href="/cgu">Conditions d’utilisation</Link> · <Link href="/privacy">Confidentialité</Link></div></footer>
</div></div>}
