"use client";
import { useEffect, useMemo, useState } from "react";
import { Headset, X, Send } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Ticket={id:string;subject:string;message:string;status:string;created_at:string};
type ChatMessage={id:string;sender_role:string;body:string;created_at:string};
type Notice={id:string;title:string;message:string;read_at?:string|null};
export default function InvestProHelpCenter(){
 const db=useMemo(()=>createClient(),[]);
 const [open,setOpen]=useState(false),[tab,setTab]=useState<"help"|"notices">("help");
 const [subject,setSubject]=useState("InvestPro Copier"),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState("");
 const [tickets,setTickets]=useState<Ticket[]>([]),[notices,setNotices]=useState<Notice[]>([]),[active,setActive]=useState<string|null>(null),[messages,setMessages]=useState<ChatMessage[]>([]);
 async function headers():Promise<Record<string,string>>{const {data:{session}}=await db.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(){try{const h=await headers();const [t,n]=await Promise.all([fetch("/api/support/ticket",{headers:h,cache:"no-store"}),fetch("/api/notifications",{cache:"no-store"})]);if(t.ok)setTickets((await t.json()).tickets||[]);if(n.ok)setNotices((await n.json()).notifications||[])}catch{}}
 async function loadChat(id:string){try{const r=await fetch(`/api/support/messages?ticket_id=${encodeURIComponent(id)}`,{headers:await headers(),cache:"no-store"});const j=await r.json();if(r.ok)setMessages(j.messages||[]);else setFeedback(j.error||"Historique indisponible")}catch{setFeedback("Historique indisponible")}}
 useEffect(()=>{void load();const timer=setInterval(()=>{void load();if(active)void loadChat(active)},20000);return()=>clearInterval(timer)},[active]);
 async function send(){if(draft.trim().length<(active?1:10)){setFeedback("Écris un message plus détaillé.");return;}setBusy(true);setFeedback("");try{
 const r=await fetch(active?"/api/support/messages":"/api/support/ticket",{method:"POST",headers:{...(await headers()),"Content-Type":"application/json"},body:JSON.stringify(active?{ticket_id:active,message:draft}:{subject,message:draft})});const j=await r.json();if(!r.ok)throw Error(j.error||"Envoi impossible");setDraft("");if(!active&&j.ticket?.id){setActive(j.ticket.id);await loadChat(j.ticket.id)}else if(active)await loadChat(active);await load();setFeedback("Message envoyé.")
 }catch(e){setFeedback(e instanceof Error?e.message:"Erreur d’envoi")}finally{setBusy(false)}}
 const unread=notices.filter(x=>!x.read_at).length;
 return <div className="fixed bottom-20 right-4 z-[1000] md:bottom-6 md:right-6">
 {open?<section className="mb-3 flex max-h-[75vh] w-[min(385px,calc(100vw-32px))] flex-col rounded-2xl border border-amber-500/30 bg-[#0b0e0c] p-4 text-white shadow-2xl">
 <header className="flex items-center justify-between"><strong className="text-sm">Assistance InvestPro</strong><button onClick={()=>setOpen(false)} aria-label="Fermer"><X size={16}/></button></header>
 <nav className="my-3 flex gap-2"><button onClick={()=>setTab("help")} className={`rounded-lg px-3 py-2 text-xs ${tab==="help"?"bg-amber-400 text-black":"bg-white/10"}`}>Support</button><button onClick={()=>setTab("notices")} className={`rounded-lg px-3 py-2 text-xs ${tab==="notices"?"bg-amber-400 text-black":"bg-white/10"}`}>Notifications ({unread})</button></nav>
 {tab==="help"?<><div className="mb-2 flex items-center justify-between text-xs"><strong>{active? tickets.find(t=>t.id===active)?.subject||"Conversation":"Nouvelle conversation"}</strong>{active?<button className="text-amber-300" onClick={()=>{setActive(null);setDraft("");setMessages([])}}>← Mes demandes</button>:null}</div>
 {active?<div className="mb-2 min-h-28 space-y-2 overflow-y-auto rounded-lg border border-white/10 p-2" style={{maxHeight:"32vh"}}>{messages.map(m=><div key={m.id} className={`flex ${m.sender_role==="client"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] rounded-xl p-2 text-xs ${m.sender_role==="client"?"bg-amber-500/20":"bg-white/10"}`}><div className="mb-1 text-[10px] text-amber-200">{m.sender_role==="client"?"Vous":"Support InvestPro"}</div><p className="whitespace-pre-wrap break-words">{m.body}</p><div className="mt-1 text-[9px] text-white/40">{new Date(m.created_at).toLocaleString("fr-FR")}</div></div></div>)}{!messages.length?<div className="text-xs text-white/50">Chargement de la conversation…</div>:null}</div>:<><p className="mb-2 text-xs text-white/60">Une question ? Notre équipe vous répond ici.</p><select aria-label="Sujet" value={subject} onChange={e=>setSubject(e.target.value)} className="mb-2 w-full rounded-lg border border-white/20 bg-[#111] p-2 text-xs"><option>InvestPro Copier</option><option>Connexion MT4/MT5</option><option>Mon compte</option><option>Autre question</option></select></>}
 <textarea aria-label="Votre message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={8000} rows={3} placeholder="Écrire un message…" className="w-full rounded-lg border border-white/20 bg-[#111] p-2 text-xs"/><button disabled={busy||!draft.trim()} onClick={()=>void send()} className="mt-2 flex justify-center gap-2 rounded-lg bg-amber-400 p-2 text-xs font-bold text-black disabled:opacity-40"><Send size={14}/>{busy?"Envoi…":"Envoyer"}</button>
 {feedback?<p role="status" className="mt-2 text-xs text-amber-200">{feedback}</p>:null}
 {!active?<div className="mt-3 max-h-36 overflow-y-auto border-t border-white/10 pt-2"><div className="mb-1 text-xs font-semibold">Mes conversations</div>{tickets.map(t=><button key={t.id} onClick={()=>{setActive(t.id);setFeedback("");void loadChat(t.id)}} className="mb-1 block w-full rounded-lg bg-white/5 p-2 text-left text-xs"><strong>{t.subject}</strong> · {t.status}<div className="text-white/50">{new Date(t.created_at).toLocaleDateString("fr-FR")}</div></button>)}</div>:null}</>:<div className="max-h-56 overflow-y-auto">{notices.map(n=><div key={n.id} className="mb-2 rounded-lg bg-white/5 p-2 text-xs"><strong>{n.title}</strong><p>{n.message}</p></div>)}{!notices.length?<p className="text-xs text-white/60">Aucune notification.</p>:null}</div>}
 </section>:null}
 <button onClick={()=>{setOpen(!open);if(!open)void load()}} className="relative flex items-center gap-2 rounded-full border border-amber-500/50 bg-[#171811] px-4 py-3 text-sm font-semibold text-amber-300 shadow-2xl"><Headset size={19}/>Support{unread>0?<span className="rounded-full bg-amber-400 px-2 text-xs text-black">{unread}</span>:null}</button></div>
}
