'use client';
import {useEffect,useState,useCallback} from 'react';
import type {Trade} from '@/lib/telegram/engine';
type Data={trades:Trade[];issues:{message:number;reason:string}[];reviewCount:number;lastReceived:string|null;admin:boolean;preview?:boolean};
export default function VipTelegram(){
 const [preview,setPreview]=useState(false),[checked,setChecked]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false);
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[connection,setConnection]=useState(''),[month,setMonth]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit'}).format(new Date()));
 const load=useCallback(async()=>{setRefreshing(true);try{
 const r=await fetch('/api/telegram/stats',{cache:'no-store'}),j=await r.json();setPreview(Boolean(j.preview));
 if(!r.ok)throw Error(j.error||'Lecture des statistiques indisponible');
 setData(j);setError('');setChecked(new Date().toISOString());
 if(j.admin){try{const response=await fetch('/api/telegram/manage',{cache:'no-store'});const status=await response.json();setConnection(!response.ok?'Configuration impossible à vérifier':status.configured?`Adresse de réception enregistrée · ${status.pending??0} message(s) en attente${status.lastErrorAt?' · une erreur de livraison a été signalée':''}`:'Adresse de réception non connectée à ce site');}catch{setConnection('Vérification de la connexion indisponible');}}
 else setConnection('Vérification de la connexion réservée à l’administrateur');
 }catch(e){setError((e as Error).message||'Connexion indisponible');setConnection('État non vérifié');}finally{setRefreshing(false);}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>{void load();},30000);return()=>clearInterval(id);},[load]);
 async function connect(){setBusy(true);setNotice('');try{const r=await fetch('/api/telegram/manage',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error);setNotice(j.message);await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const rows=(data?.trades??[]).filter(t=>t.date.startsWith(month)),wins=rows.filter(t=>t.status==='win'),losses=rows.filter(t=>t.status==='loss'),closed=wins.length+losses.length,total=rows.reduce((n,t)=>n+(t.r??0),0);
 return <section className="tg-vip" aria-label="Statistiques Telegram"><div className="tg-head"><div><small>TELEGRAM · SUIVI AUTOMATIQUE</small><h2>Les signaux du VIP</h2><p>Performance théorique au meilleur TP annoncé.</p></div><label>Mois du signal<input aria-label="Mois des statistiques Telegram" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>
 <div className="tg-admin" aria-live="polite"><div className="tg-head"><h3>Connexion du canal Telegram</h3><span className="tg-badge">{error?'À vérifier':!data?'Vérification…':data.lastReceived?'Réception confirmée':'Réception à tester'}</span></div>
 <p>{connection||'Vérification en cours…'}</p>
 {preview&&<p className="tg-info">Vous êtes sur la version de test. Sa configuration peut différer du site principal. La connexion du bot se gère sur <a href="https://www.investprotrading.fr/dashboard/performances-vip" target="_blank" rel="noopener noreferrer">InvestPro en production ↗</a>.</p>}
 {error&&<p role="alert">{error} {preview?'Vérifiez les droits Telegram et les variables de cet environnement dans Vercel. Cette erreur ne prouve pas que le bot du site principal est déconnecté.':'Vérifiez les droits du compte connecté et la configuration Telegram dans Vercel.'} {data?'Les chiffres conservés ci-dessous ne sont pas à jour.':''}</p>}
 <div className="tg-dates"><p><span>Dernier message reçu du canal</span><strong>{data?.lastReceived?new Date(data.lastReceived).toLocaleString('fr-FR',{timeZone:'Europe/Paris'}):error?'Indisponible':data?'Aucun message reçu':'Chargement…'}</strong></p><p><span>Dernière lecture des statistiques</span><strong>{checked?new Date(checked).toLocaleString('fr-FR',{timeZone:'Europe/Paris'}):'Pas encore effectuée'}</strong></p></div>
 <p>Actualisation toutes les 30 secondes · Heure de Paris. Un message ordinaire permet de vérifier la réception ; seuls les signaux reconnus alimentent les statistiques.</p>
 <button disabled={refreshing} onClick={()=>void load()}>{refreshing?'Vérification…':'Vérifier / actualiser'}</button>
 {data?.admin&&!preview&&!error&&<button disabled={busy} onClick={connect}>{busy?'Connexion…':'Connecter / rétablir Telegram'}</button>}
 {notice&&<p role="status">{notice}</p>}
 </div>
 {data&&<><div className="tg-cards">{[['Bilan mensuel',`${total>=0?'+':''}${total.toFixed(2)} R`],['Winrate',closed?`${(100*wins.length/closed).toFixed(1)} %`:'—'],['Gagnants / perdants',`${wins.length} / ${losses.length}`],['En attente / à vérifier',`${rows.filter(t=>t.status==='pending').length} / ${rows.filter(t=>t.status==='review').length}`]].map(([title,v])=><div key={title}><span>{title}</span><strong>{v}</strong></div>)}</div>

 <div className="tg-scroll"><table><thead><tr>{['Date','Signal','Entrée moyenne','Stop initial','Plus haut TP','Résultat'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.asset} · {t.side}</td><td>{t.entry.toFixed(3)}</td><td>{t.sl}</td><td>{t.target?`TP${t.target}`:'—'}</td><td>{t.status==='review'?'À vérifier':t.r===null?'En attente':`${t.r.toFixed(2)} R`}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Aucun signal reçu pour ce mois.</p>}
 {data.admin&&data.issues.length>0&&<details><summary>{data.reviewCount} message(s) à vérifier</summary><ul>{data.issues.map(i=><li key={i.message}>Message {i.message} : {i.reason}</li>)}</ul><p>Corrige le message sur Telegram. Pour une réponse au mauvais signal, modifie l’ancienne réponse en « ANNULÉ », puis publie une nouvelle réponse au bon signal. La suppression Telegram seule ne corrige pas les statistiques.</p></details>}</>}

 <details><summary>Méthode et limites</summary><p>Une entrée de référence au milieu de la zone. Un signal = un trade. Le RR du TP le plus haut annoncé remplace celui du TP précédent, sans cumul. Un SL sans TP vaut −1R. Aucun résultat en euros n’est déduit de ces annonces.</p><p>Winrate = gagnants / (gagnants + perdants). Les signaux en attente ou contradictoires sont exclus. Mois de publication du signal, fuseau Europe/Paris. Les modifications reçues recalculent les résultats ; la suppression des messages et l’historique ancien ne sont pas récupérés automatiquement.</p><p>Réponds au signal d’origine avec « TP1 TOUCHER », « TP2 touché » ou « Stop loss touché ». Les commentaires du groupe de discussion, messages privés, captures sans légende et annonces ambiguës ne sont pas automatiquement comptabilisés. Ces chiffres sont séparés du suivi manuel ci-dessous.</p></details>
 <style jsx>{`.tg-vip{padding:24px;border:1px solid var(--gold-border,#70552a);background:var(--card,#111);border-radius:20px;margin-bottom:28px;color:var(--text,#eee)}.tg-head{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.tg-vip h2{font-size:26px;font-weight:700}.tg-vip h3{font-size:18px;font-weight:600}.tg-vip p{font-size:14px;line-height:1.6;margin:12px 0}.tg-vip small{color:var(--gold,#e8b95f);letter-spacing:.12em}.tg-vip input{display:block;color:inherit;background:transparent;border:1px solid #555;padding:10px;border-radius:8px;font-size:16px}.tg-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.tg-cards>div{padding:18px;background:#ffffff08;border-radius:12px}.tg-cards span{display:block;font-size:14px}.tg-cards strong{display:block;font-size:26px;margin-top:8px}.tg-scroll{overflow-x:auto}.tg-vip table{width:100%;border-collapse:collapse;font-size:14px}.tg-vip td,.tg-vip th{text-align:left;padding:12px;border-bottom:1px solid #ffffff20;white-space:nowrap}.tg-vip button{min-height:44px;padding:10px 16px;border:1px solid var(--gold-border,#70552a);border-radius:8px;margin:8px 8px 8px 0}.tg-vip button:disabled{opacity:.5}.tg-admin{margin:18px 0;padding:18px;border:1px solid #ffffff20;border-radius:12px}.tg-vip summary{cursor:pointer;padding:10px 0;min-height:44px}.tg-vip li{margin:8px 0}.tg-badge{padding:6px 12px;border:1px solid #ffc86750;border-radius:99px;color:#ffc867;font-size:12px}.tg-info{padding:12px;background:#ffc8670d;border-radius:10px}.tg-vip a{text-decoration:underline;color:#ffc867}.tg-dates{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}.tg-dates span,.tg-dates strong{display:block}.tg-dates span{color:#aaa;font-size:12px}.tg-dates strong{font-size:14px;margin-top:4px}@media(max-width:700px){.tg-cards{grid-template-columns:1fr 1fr}.tg-vip{padding:16px}.tg-cards strong{font-size:21px}}`}</style></section>;
}
