'use client';
import {useEffect,useState,useCallback} from 'react';
import type {Trade} from '@/lib/telegram/engine';
type Data={trades:Trade[];issues:{message:number;reason:string}[];reviewCount:number;lastReceived:string|null;admin:boolean};
export default function VipTelegram(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[connection,setConnection]=useState(''),[month,setMonth]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit'}).format(new Date()));
 const load=useCallback(async()=>{try{const r=await fetch('/api/telegram/stats',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('');if(j.admin){const s=await fetch('/api/telegram/manage',{cache:'no-store'});const status=await s.json();setConnection(!s.ok?'Configuration à vérifier':status.configured?`Webhook enregistré · ${status.pending} message(s) en attente${status.lastErrorAt?' · erreur de livraison à vérifier':''}`:'Webhook non connecté');}}catch(e){setError((e as Error).message||'Connexion indisponible');}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>{void load();},30000);return()=>clearInterval(id);},[load]);
 async function connect(){setBusy(true);setNotice('');try{const r=await fetch('/api/telegram/manage',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error);setNotice(j.message);await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const rows=(data?.trades??[]).filter(t=>t.date.startsWith(month)),wins=rows.filter(t=>t.status==='win'),losses=rows.filter(t=>t.status==='loss'),closed=wins.length+losses.length,total=rows.reduce((n,t)=>n+(t.r??0),0);
 return <section className="tg-vip" aria-label="Statistiques Telegram"><div className="tg-head"><div><small>TELEGRAM · SUIVI AUTOMATIQUE</small><h2>Les signaux du VIP</h2><p>Performance théorique au meilleur TP annoncé.</p></div><label>Mois du signal<input aria-label="Mois des statistiques Telegram" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>
 {error?<p role="alert">{error} Les dernières données éventuellement affichées ne sont pas à jour.</p>:!data?<p>Chargement…</p>:null}
 {data&&<><div className="tg-cards">{[['Bilan mensuel',`${total>=0?'+':''}${total.toFixed(2)} R`],['Winrate',closed?`${(100*wins.length/closed).toFixed(1)} %`:'—'],['Gagnants / perdants',`${wins.length} / ${losses.length}`],['En attente / à vérifier',`${rows.filter(t=>t.status==='pending').length} / ${rows.filter(t=>t.status==='review').length}`]].map(([title,v])=><div key={title}><span>{title}</span><strong>{v}</strong></div>)}</div>
 <p>Dernier message reçu : {data.lastReceived?new Date(data.lastReceived).toLocaleString('fr-FR',{timeZone:'Europe/Paris'}):'aucun — réception à tester'}. Actualisation toutes les 30 secondes.</p>
 <div className="tg-scroll"><table><thead><tr>{['Date','Signal','Entrée moyenne','Stop initial','Plus haut TP','Résultat'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.asset} · {t.side}</td><td>{t.entry.toFixed(3)}</td><td>{t.sl}</td><td>{t.target?`TP${t.target}`:'—'}</td><td>{t.status==='review'?'À vérifier':t.r===null?'En attente':`${t.r.toFixed(2)} R`}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Aucun signal reçu pour ce mois.</p>}
 {data.admin&&<div className="tg-admin"><h3>Connexion du canal</h3><p>{connection}</p><button disabled={busy} onClick={connect}>{busy?'Connexion…':'Connecter Telegram'}</button><button onClick={()=>void load()}>Actualiser</button>{notice&&<p role="status">{notice}</p>}{data.issues.length>0&&<details><summary>{data.reviewCount} message(s) à vérifier</summary><ul>{data.issues.map(i=><li key={i.message}>Message {i.message} : {i.reason}</li>)}</ul><p>Corrige le message sur Telegram. Pour une réponse au mauvais signal, modifie l’ancienne réponse en « ANNULÉ », puis publie une nouvelle réponse au bon signal. La suppression Telegram seule ne corrige pas les statistiques.</p></details>}</div>}</>}
 <details><summary>Méthode et limites</summary><p>Une entrée de référence au milieu de la zone. Un signal = un trade. Le RR du TP le plus haut annoncé remplace celui du TP précédent, sans cumul. Un SL sans TP vaut −1R. Aucun résultat en euros n’est déduit de ces annonces.</p><p>Winrate = gagnants / (gagnants + perdants). Les signaux en attente ou contradictoires sont exclus. Mois de publication du signal, fuseau Europe/Paris. Les modifications reçues recalculent les résultats ; la suppression des messages et l’historique ancien ne sont pas récupérés automatiquement.</p><p>Réponds au signal d’origine avec « TP1 TOUCHER », « TP2 touché » ou « Stop loss touché ». Les commentaires du groupe de discussion, messages privés, captures sans légende et annonces ambiguës ne sont pas automatiquement comptabilisés. Ces chiffres sont séparés du suivi manuel ci-dessous.</p></details>
 <style jsx>{`.tg-vip{padding:24px;border:1px solid var(--gold-border,#70552a);background:var(--card,#111);border-radius:20px;margin-bottom:28px;color:var(--text,#eee)}.tg-head{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.tg-vip h2{font-size:26px;font-weight:700}.tg-vip h3{font-size:18px;font-weight:600}.tg-vip p{font-size:14px;line-height:1.6;margin:12px 0}.tg-vip small{color:var(--gold,#e8b95f);letter-spacing:.12em}.tg-vip input{display:block;color:inherit;background:transparent;border:1px solid #555;padding:10px;border-radius:8px;font-size:16px}.tg-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.tg-cards>div{padding:18px;background:#ffffff08;border-radius:12px}.tg-cards span{display:block;font-size:14px}.tg-cards strong{display:block;font-size:26px;margin-top:8px}.tg-scroll{overflow-x:auto}.tg-vip table{width:100%;border-collapse:collapse;font-size:14px}.tg-vip td,.tg-vip th{text-align:left;padding:12px;border-bottom:1px solid #ffffff20;white-space:nowrap}.tg-vip button{min-height:44px;padding:10px 16px;border:1px solid var(--gold-border,#70552a);border-radius:8px;margin:8px 8px 8px 0}.tg-vip button:disabled{opacity:.5}.tg-admin{margin:18px 0;padding:18px;border:1px solid #ffffff20;border-radius:12px}.tg-vip summary{cursor:pointer;padding:10px 0;min-height:44px}.tg-vip li{margin:8px 0}@media(max-width:700px){.tg-cards{grid-template-columns:1fr 1fr}.tg-vip{padding:16px}.tg-cards strong{font-size:21px}}`}</style></section>;
}
