'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Plus,Wallet,ArrowRight,ArrowUpRight,ShieldCheck,Target,TrendingUp,Activity,BookOpen,CalendarDays} from 'lucide-react';
import EquityChart from './EquityChart';
type Account={id:number;name:string;currency:string;current_balance:number;platform:string|null};
type Trade={id:number;account_id:number|null;trade_date:string;symbol:string;direction:string;result_amount:number;result_r:number;status:string;risk_percent:number};
type Plan={max_risk_percent:number;max_trades_per_day:number;minimum_rr:number}|null;
type Props={profile:{username:string;plan:string};accounts:Account[];trades:Trade[];plan:Plan;compliantIds:number[];events:{id:string;time:string;currency:string;title:string}[];calendarLoading:boolean};
function parisDate(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const d=new Date(value);if(!Number.isFinite(d.getTime()))return '';return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export default function Dashboard({profile,accounts,trades,plan,compliantIds,events,calendarLoading}:Props){
 const [account,setAccount]=useState('all'),[period,setPeriod]=useState('month');const today=parisDate(new Date().toISOString());
 const selectedAccounts=accounts.filter(a=>account==='all'||String(a.id)===account);
 const currencies=[...new Set(selectedAccounts.map(a=>a.currency))];const currency=currencies.length===1?currencies[0]:null;
 const money=(n:number,c:string|null=currency)=>c?new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:2}).format(n):'Devises multiples';
 const selected=trades.filter(t=>(account==='all'||String(t.account_id)===account)&&(period==='all'||parisDate(t.trade_date).slice(0,7)===today.slice(0,7)));
 const closed=selected.filter(t=>['win','loss','breakeven'].includes(t.status)).sort((a,b)=>a.trade_date.localeCompare(b.trade_date)||a.id-b.id);
 const pnl=closed.reduce((s,t)=>s+Number(t.result_amount||0),0),wins=closed.filter(t=>t.status==='win').length,losses=closed.filter(t=>t.status==='loss').length;
 const ids=new Set(compliantIds),discipline=plan&&selected.length?selected.filter(t=>ids.has(t.id)).length/selected.length*100:null;
 const risk=selected.filter(t=>Number(t.risk_percent)>0);const avgRisk=risk.length?risk.reduce((s,t)=>s+Number(t.risk_percent),0)/risk.length:null;
 let balance=0;const values=[0,...closed.map(t=>balance+=Number(t.result_amount||0))];
 const fmt=(n:number|null)=>n===null?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n)+' %';
 const limits=[['Risque maximum / trade',plan?fmt(plan.max_risk_percent):'À définir'],['Trades maximum / jour',plan?String(plan.max_trades_per_day):'À définir'],['Ratio minimum visé',plan?'1:'+plan.minimum_rr:'À définir']];
 const metricData=[{label:'Solde des comptes',value:accounts.length?money(selectedAccounts.reduce((s,a)=>s+Number(a.current_balance||0),0)):'—',detail:selectedAccounts.length+' compte(s) sélectionné(s)',icon:Wallet},{label:'Résultat net',value:closed.length?money(pnl):'—',detail:'Trades clôturés de la période',icon:TrendingUp},{label:'Taux de réussite',value:fmt(wins+losses?wins/(wins+losses)*100:null),detail:`${wins} gagnants · ${losses} perdants · hors BE`,icon:Target},{label:'Trades de la période',value:String(selected.length),detail:`${closed.length} clôturés`,icon:Activity},{label:'Discipline',value:fmt(discipline),detail:plan?'Selon votre plan actuel':'Plan à définir',icon:ShieldCheck},{label:'Risque moyen',value:fmt(avgRisk),detail:'Risque renseigné dans le journal',icon:BookOpen}];
 return <div className="aura-faithful"><div className="page-heading"><div><span className="eyebrow">VOTRE TRADING, EN PERSPECTIVE</span><h1>Bonjour, {profile.username}<span className="greeting-period">.</span></h1><p>Gardez une vue claire sur vos résultats et vos prochaines décisions.</p></div><Link className="btn primary" href="/dashboard/journal#nouveau"><Plus size={16}/>Ajouter un trade</Link></div>
 <section className="welcome-banner"><div><span className="eyebrow">INVESTPRO TRADING HUB</span><h2>Votre discipline fait <em>la différence.</em></h2><p>Apprenez, analysez et suivez votre trading au même endroit.</p><div><Link className="btn primary" href="/dashboard/comptes"><Wallet size={16}/>Mes comptes</Link><Link className="btn" href="/dashboard/academy">Mes formations <ArrowRight size={16}/></Link></div></div><div className="welcome-rules"><span>LES REPÈRES DU PLAN</span>{limits.map(([label,value])=><div key={label}><b>{value}</b><small>{label}</small></div>)}</div></section>
 <div className="filterbar"><div className="filter-left"><select className="picker" aria-label="Compte affiché" value={account} onChange={e=>setAccount(e.target.value)}><option value="all">Tous mes comptes</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.platform||a.currency}</option>)}</select><span className="subtle-status"><span/>Données de votre journal</span></div><select className="picker" aria-label="Période" value={period} onChange={e=>setPeriod(e.target.value)}><option value="month">{new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric',timeZone:'Europe/Paris'}).format(new Date())}</option><option value="all">Tout l’historique</option></select></div>
 <div className="metrics">{metricData.map(m=><div className="metric" key={m.label}><div className="metric-label">{m.label}<m.icon size={17}/></div><strong>{m.value}</strong><div className="muted">{m.detail}</div></div>)}</div>
 <div className="dashboard-grid"><section className="panel equity-panel"><div className="panel-heading"><div><span className="eyebrow">ÉVOLUTION DU COMPTE</span><h2>La régularité se construit.</h2></div><span className="tag">{closed.length} trades clôturés</span></div><div className="chart-summary"><strong className={pnl>=0?'positive':'negative'}>{closed.length?money(pnl):'—'}</strong><span>de résultat net réalisé</span></div>{currency?<EquityChart values={values} currency={currency} labels={closed.map(t=>parisDate(t.trade_date))}/>:<div className="equity-chart aura-empty-chart">Sélectionnez un compte pour afficher sa courbe dans sa devise.</div>}<div className="chart-footer"><span>Résultat cumulé · hors positions ouvertes et dépôts</span><Link href="/dashboard/journal">Analyser mes trades <ArrowUpRight size={15}/></Link></div></section>
 <section className="panel session-panel"><div className="panel-heading"><h2>Votre cap du jour</h2><ShieldCheck size={19}/></div><div className="session-date">{new Intl.DateTimeFormat('fr-FR',{dateStyle:'full',timeZone:'Europe/Paris'}).format(new Date()).toUpperCase()}</div>{limits.map(([label,value])=><div className="rule-line" key={label}><span>{label}</span><b>{value}</b></div>)}<div className="session-quote">« Le bon trade est celui<br/>qui respecte votre plan. »</div><Link className="text-link" href="/dashboard/plan">Préparer ma session <ArrowRight size={16}/></Link></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><h2>Derniers trades</h2><Link className="text-link" href="/dashboard/journal">Tout voir <ArrowRight size={15}/></Link></div><div className="aura-table-scroll"><table className="aura-trades"><thead><tr><th>Instrument</th><th>Date</th><th>Résultat net</th><th>R multiple</th><th>Discipline</th></tr></thead><tbody>{[...selected].sort((a,b)=>b.trade_date.localeCompare(a.trade_date)||b.id-a.id).slice(0,4).map(t=>{const c=accounts.find(a=>a.id===t.account_id)?.currency||null,done=['win','loss','breakeven'].includes(t.status);return <tr key={t.id}><td><Link href="/dashboard/journal" className="symbol"><span className={'asset-icon '+(/GOLD|XAU/.test(t.symbol)?'gold-asset':'')}>{/GOLD|XAU/.test(t.symbol)?'Au':t.symbol.slice(0,2)}</span><span><b>{t.symbol}</b><small>{t.direction==='buy'?'Achat':'Vente'}</small></span></Link></td><td>{parisDate(t.trade_date)}</td><td className={t.result_amount>0?'positive':t.result_amount<0?'negative':''}>{done?money(t.result_amount,c):t.status==='open'?'Ouvert':'Annulé'}</td><td>{done&&t.result_r!=null?Number(t.result_r).toFixed(2)+' R':'—'}</td><td><span className={'tag '+(ids.has(t.id)?'green':'orange')}>{!plan?'Non évalué':ids.has(t.id)?'Respecté':'À revoir'}</span></td></tr>})}</tbody></table></div>{!selected.length&&<div className="aura-empty-chart">Aucun trade sur cette période. Retrouvez votre historique dans le journal.</div>}</section><section className="vip-card"><div className="vip-monogram">IP<span>VIP</span></div><span className="eyebrow">L’ESPACE INVESTPRO VIP</span><h2>Une stratégie.<br/>Une vision partagée.</h2><p>Explorez le suivi des performances du groupe et le futur parcours de copie.</p><Link href="/dashboard/performances-vip">Découvrir les performances <ArrowUpRight size={17}/></Link></section></div>
 <div className="dashboard-extras aura-live-extras"><section className="panel"><div className="panel-heading"><h2>Vos comptes</h2><Wallet size={18}/></div>{selectedAccounts.map(a=><Link className="rule-line" key={a.id} href="/dashboard/comptes"><span>{a.name}</span><b>{money(a.current_balance,a.currency)}</b></Link>)}{!accounts.length&&<p>Aucun compte ajouté.</p>}<Link className="text-link" href="/dashboard/comptes">Gérer mes comptes <ArrowRight size={16}/></Link></section><section className="panel"><div className="panel-heading"><h2>Marchés aujourd’hui</h2><CalendarDays size={18}/></div>{calendarLoading?<p>Chargement du calendrier…</p>:events.length?events.slice(0,3).map(e=><div className="rule-line" key={e.id}><span>{e.time} · {e.currency}</span><b>{e.title}</b></div>):<p>Aucune annonce à afficher. Consultez le calendrier pour vérifier les événements.</p>}<Link className="text-link" href="/dashboard/calendrier">Voir le calendrier <ArrowRight size={16}/></Link></section><section className="panel"><div className="panel-heading"><h2>Votre progression</h2><Target size={18}/></div><p>Retrouvez vos objectifs, vos limites et votre bilan dans vos outils.</p><Link className="rule-line" href="/dashboard/plan">Mon plan de trading <ArrowRight size={16}/></Link><Link className="rule-line" href="/dashboard/rapports">Mes rapports <ArrowRight size={16}/></Link><Link className="rule-line" href="/dashboard/academy">Mes formations <ArrowRight size={16}/></Link></section></div>
 </div>
}
