'use client';
import {useEffect,useRef,useState} from 'react';
import {ExternalLink,RefreshCw} from 'lucide-react';
declare global {interface Window {FJWidgets?:{createWidget:new(options:Record<string,string>)=>unknown}}}
const sources={tradingview:{name:'TradingView',url:'https://www.tradingview.com/chart/'},calendrier:{name:'Investing.com',url:'https://fr.investing.com/economic-calendar/'},financialjuice:{name:'FinancialJuice',url:'https://www.financialjuice.com/home'}};
export default function MarketWidget({kind}:{kind:keyof typeof sources}){
 const host=useRef<HTMLDivElement>(null);const [retry,setRetry]=useState(0);const [error,setError]=useState(false);const source=sources[kind];
 useEffect(()=>{const root=host.current;if(!root||kind==='calendrier')return;setError(false);let cancelled=false;root.replaceChildren();const script=document.createElement('script');script.async=true;
 if(kind==='tradingview'){
 const widget=document.createElement('div');widget.className='tradingview-widget-container__widget';widget.style.cssText='height:calc(100% - 32px);width:100%';root.appendChild(widget);
 const credit=document.createElement('div');credit.className='tradingview-widget-copyright';const a=document.createElement('a');a.href='https://www.tradingview.com/symbols/OANDA-XAUUSD/';a.target='_blank';a.rel='noopener nofollow';a.textContent='XAUUSD chart by TradingView';credit.appendChild(a);root.appendChild(credit);
 script.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';script.text=JSON.stringify({autosize:true,symbol:'OANDA:XAUUSD',interval:'60',timezone:'Europe/Paris',theme:'dark',style:'1',locale:'fr',allow_symbol_change:true,hide_top_toolbar:false,hide_side_toolbar:false,hide_legend:false,save_image:true,calendar:false,withdateranges:true,backgroundColor:'#0b0d0b',gridColor:'rgba(255,200,103,0.05)',support_host:'https://www.tradingview.com'});root.appendChild(script);
 }else{
 const widget=document.createElement('div');widget.id='financialjuice-news-widget-container';root.appendChild(widget);
 const render=()=>{if(cancelled)return;try{if(!window.FJWidgets)throw new Error('Widget unavailable');new window.FJWidgets.createWidget({container:widget.id,mode:'Dark',width:'100%',height:'760px',backColor:'0b0d0b',fontColor:'deded8',widgetType:'NEWS'});}catch{setError(true);}};
 if(window.FJWidgets)render();else{script.src='https://feed.financialjuice.com/widgets/widgets.js';script.onload=render;root.appendChild(script);}
 }
 script.onerror=()=>{if(!cancelled)setError(true);};return()=>{cancelled=true;script.onload=null;script.onerror=null;root.replaceChildren();};
 },[kind,retry]);
 return <section className="panel external-market"><div className="external-market-toolbar"><div><span className="eyebrow">SOURCE · {source.name.toUpperCase()}</span><p>{kind==='tradingview'?'Graphique interactif · GOLD par défaut · Heure de Paris':kind==='calendrier'?'Annonces économiques, résultats, prévisions et chiffres précédents.':'Titres et actualités des marchés · Flux en anglais'}</p></div><div><button className="btn" onClick={()=>{setError(false);setRetry(n=>n+1)}} aria-label={'Recharger '+source.name}><RefreshCw size={16}/></button><a className="btn" href={source.url} target="_blank" rel="noopener noreferrer">Ouvrir {source.name}<ExternalLink size={16}/></a></div></div>{error&&<div className="notice" role="alert">Le widget n’a pas pu être chargé. Réessayez ou ouvrez directement {source.name} avec le bouton ci-dessus.</div>}{kind==='calendrier'?<div className="calendar-embed"><iframe key={retry} title="Calendrier économique Investing.com" src="https://sslecal2.investing.com?columns=exc_flags,exc_currency,exc_importance,exc_actual,exc_forecast,exc_previous&features=datepicker,timezone,timeselector,filters&calType=week&lang=5" width="100%" height="800"/><p className="widget-credit">Calendrier économique fourni par <a href="https://fr.investing.com/" target="_blank" rel="nofollow noopener noreferrer">Investing.com France</a>, portail de la bourse.</p></div>:<div ref={host} className={'live-widget '+(kind==='tradingview'?'tradingview-widget-container':'financialjuice-widget')}/> }<p className="widget-help">{kind==='calendrier'?'Vérifiez le fuseau horaire affiché dans le calendrier avant votre session. ':kind==='tradingview'?'Les cotations et leur éventuel délai dépendent de l’instrument et de TradingView. ':'La disponibilité et le délai des actualités dépendent de FinancialJuice. '}Si le contenu reste vide, ouvrez le service avec le bouton ci-dessus. </p></section>;
}
