'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {isClosed,tradeDay,performanceSummary,type PerformanceAccount,type PerformanceTrade} from '@/lib/performance';
const signed=(v:number,suffix:string)=>`${v>0?'+':''}${v.toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})}${suffix}`;
export default function PerformanceCalendar({trades,accounts,accountId='all',accountPicker=false}:{trades:PerformanceTrade[];accounts:PerformanceAccount[];accountId?:number|'all';accountPicker?:boolean}){
 const [localAccount,setLocalAccount]=useState('all');
 const scope=accountPicker?localAccount:String(accountId);
 const scopedAccounts=useMemo(()=>accounts.filter(a=>scope==='all'||String(a.id)===scope),[accounts,scope]);
 const closed=useMemo(()=>trades.filter(t=>isClosed(t)&&(scope==='all'||String(t.account_id)===scope)&&tradeDay(t.trade_date)),[trades,scope]);
 const latest=closed.map(t=>tradeDay(t.trade_date)).sort().at(-1)?.slice(0,7)||tradeDay(new Date().toISOString()).slice(0,7);
 const [month,setMonth]=useState(latest);
 useEffect(()=>setMonth(latest),[latest,scope]);
 const monthly=closed.filter(t=>tradeDay(t.trade_date).startsWith(month));
 const total=performanceSummary(monthly,scopedAccounts);
 const [year,m]=month.split('-').map(Number),first=new Date(year,m-1,1,12),offset=(first.getDay()+6)%7;
 const days=Array.from({length:Math.ceil((offset+new Date(year,m,0).getDate())/7)*7},(_,i)=>{const d=new Date(year,m-1,1+i-offset,12);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return {date:d,key,inMonth:d.getMonth()===m-1,result:performanceSummary(closed.filter(t=>tradeDay(t.trade_date)===key),scopedAccounts)};});
 const move=(delta:number)=>{const d=new Date(year,m-1+delta,1,12);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};
 return <section className="perf-calendar" aria-label="Calendrier de performance"><header><div><h2>Calendrier de performance</h2><p>Trades clôturés · R et % · dates en heure de Paris</p></div><div className="controls">{accountPicker&&<select aria-label="Compte du calendrier" value={localAccount} onChange={e=>setLocalAccount(e.target.value)}><option value="all">Tous les comptes</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}<button onClick={()=>move(-1)} aria-label="Mois précédent"><ChevronLeft size={18}/></button><input aria-label="Mois du calendrier" type="month" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}}/><button onClick={()=>move(1)} aria-label="Mois suivant"><ChevronRight size={18}/></button></div></header>
 <div className="grid-scroll"><div className="grid">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><div key={d} className="weekday">{d}</div>)}{days.map(({key,date,inMonth,result})=><div key={key} className={`day ${inMonth?'':'outside'} ${result.r>0?'positive':result.r<0?'negative':''}`}><span>{date.getDate()}</span>{result.count>0?<><strong>{signed(result.r,' R')}</strong><b>{result.percent===null?'— %':signed(result.percent,' %')}</b><small>{result.count} trade{result.count>1?'s':''}</small></>:<small className="empty">—</small>}</div>)}</div></div>
 <footer><span>Total du mois · {total.count} trade{total.count>1?'s':''}</span><strong>{signed(total.r,' R')} <span> / </span> {total.percent===null?'— %':signed(total.percent,' %')}</strong></footer>
 {!monthly.length&&<p>Aucun trade clôturé pour ce mois avec les filtres actuels.</p>}
 <p className="note">% = résultat monétaire ÷ capital initial {scope==='all'?'total des comptes sélectionnés':'du compte'} × 100. Base fixe, sans capitalisation ni ajustement des dépôts/retraits. Les filtres de la page s’appliquent au calendrier.</p>
 {total.percent===null&&<p className="note">Pour afficher un pourcentage, sélectionnez un compte avec un capital initial positif. Des devises différentes ou des trades sans compte empêchent le calcul global.</p>}
 <style jsx>{`.perf-calendar{border:1px solid var(--border,#655537);background:var(--panel,#111210);border-radius:24px;padding:22px;margin:20px 0;color:#eee;min-width:0}.perf-calendar header,.controls,footer{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}h2{font-size:18px;font-weight:650}p{font-size:13px;color:#aaa;line-height:1.6;margin:6px 0}button,select,input{min-height:44px;border:1px solid #ffffff20;border-radius:10px;background:#111210;color:#eee;padding:8px;font-size:14px}input{max-width:165px}select{max-width:220px}button{display:grid;place-items:center;min-width:44px}.grid-scroll{overflow-x:auto}.grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px;margin-top:22px;min-width:560px}.weekday{font-size:12px;text-align:center;color:#aaa;padding:6px}.day{border:1px solid #ffffff12;border-radius:12px;min-height:122px;padding:12px;display:flex;flex-direction:column;gap:5px}.day>span{font-size:12px;color:#aaa}.day strong{font-size:15px;margin-top:5px}.day b{font-size:13px;font-weight:500}.day small{font-size:11px;color:#aaa}.positive{background:#79e89c09;border-color:#79e89c30;color:#79e89c}.negative{background:#f4908309;border-color:#f4908330;color:#f49083}.outside{opacity:.32}.empty{margin:auto}footer{margin-top:18px;padding:14px;background:#ffffff04;border-radius:12px;font-size:14px}footer strong{color:#ffc867}.note{font-size:12px;margin-top:12px}@media(max-width:650px){.perf-calendar{padding:14px}.controls{gap:6px;width:100%}.controls select{max-width:100%;width:100%}.grid{gap:5px}.day{padding:8px}input,select{font-size:16px}}`}</style></section>;
}
