'use client';
import {useEffect,useState} from 'react';
import type {SthStatus} from '@/lib/sth/client';
export default function CopieurPage(){
 const [status,setStatus]=useState<SthStatus|null>(null),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Vérification de l’accès…'),[error,setError]=useState(false),[checked,setChecked]=useState('');
 const [platform,setPlatform]=useState('MT5'),[login,setLogin]=useState(''),[server,setServer]=useState(''),[password,setPassword]=useState(''),[lots,setLots]=useState('0.01'),[maxLots,setMaxLots]=useState(0.1),[consent,setConsent]=useState(false),[masterConsent,setMasterConsent]=useState(false),[disconnectConsent,setDisconnectConsent]=useState(false);
 const [selected,setSelected]=useState<Record<string,{on:boolean;lots:string}>>({});
 function accept(s:SthStatus){setStatus(s);setSelected(Object.fromEntries(s.masterAccountsList.map(m=>[m.id,{on:m.userIsSubscribed,lots:String(m.lots)}])));setChecked(new Date().toLocaleString('fr-FR'));setMasterConsent(false);setDisconnectConsent(false);}
 async function refresh(){setBusy(true);setError(false);try{const r=await fetch('/api/sth',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setEnabled(d.enabled);if(d.status)accept(d.status);if(d.maxLots)setMaxLots(d.maxLots);setMessage(d.message||'Statut actualisé.');}catch(e){setError(true);setMessage((e as Error).message||'Connexion indisponible.');}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 async function action(payload:Record<string,unknown>){setBusy(true);setError(false);try{const pending=fetch('/api/sth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setPassword('');setConsent(false);const r=await pending,d=await r.json();if(!r.ok)throw Error(d.error);accept(d.status);setMessage(d.message);}catch(e){setError(true);setMessage((e as Error).message||'Résultat non confirmé. Actualisez le statut avant de réessayer.');}finally{setBusy(false);}}
 return <main className="sth-page"><header><span className="eyebrow">INVESTPRO × SOCIAL TRADE HUB · PILOTE</span><h1>Copieur MT4 / MT5</h1><p>Connectez votre compte et choisissez les stratégies à copier.</p></header><section><div className="row"><h2>Connexion du compte</h2><button disabled={busy} onClick={()=>void refresh()}>{busy?'Opération en cours…':'Vérifier le statut'}</button></div><p role={error?'alert':'status'}>{message}</p>{status&&<p><strong>{error?'Dernier état connu : ':''}{status.isTradingAccountConnected?'Compte connecté':'Compte non connecté'}</strong> · Dernière vérification : {checked}</p>}<p className="muted">La connexion du copieur n’active pas la synchronisation du journal. Cette intégration reste à ajouter.</p></section>
 {enabled&&!status?.isTradingAccountConnected&&<section><h2>Relier un compte</h2><p>Commencez avec un compte de démonstration. La connexion peut démarrer la copie chez Social Trade Hub.</p><form onSubmit={e=>{e.preventDefault();void action({action:'connect',platform,login,server,password,lots,consent});}}><div className="fields"><label>Plateforme<select value={platform} onChange={e=>setPlatform(e.target.value)}><option>MT5</option><option>MT4</option></select></label><label>Numéro de compte<input required inputMode="numeric" pattern="[0-9]{1,15}" value={login} onChange={e=>setLogin(e.target.value)}/></label><label>Serveur exact du broker<input required value={server} onChange={e=>setServer(e.target.value)} placeholder="Ex. Broker-Demo" maxLength={200}/></label><label>Mot de passe MetaTrader<input required type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} maxLength={256}/></label><label>Volume fixe (lots)<input required type="number" min="0.001" max={maxLots} step="any" value={lots} onChange={e=>setLots(e.target.value)}/></label></div><p className="muted">Les identifiants sont transmis à Social Trade Hub pour connecter le compte. InvestPro ne les enregistre pas dans sa base.</p><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>J’autorise la transmission des identifiants à Social Trade Hub et la connexion du copieur, susceptible d’exécuter des ordres sur ce compte.</label><button disabled={busy||!consent||error} type="submit">Connecter ce compte</button></form></section>}
 {enabled&&status?.isTradingAccountConnected&&<><section><h2>Comptes maîtres disponibles</h2><p>Les volumes sont des lots fixes, pas un pourcentage de risque. La liste enregistrée remplace vos abonnements actuels.</p>{status.masterAccountsList.length===0&&<p>Aucun compte maître fourni par Social Trade Hub.</p>}{status.masterAccountsList.map(m=><div className="master" key={m.id}><label className="check"><input type="checkbox" checked={selected[m.id]?.on||false} onChange={e=>setSelected(s=>({...s,[m.id]:{...s[m.id],on:e.target.checked}}))}/>{m.name}</label><label>Lots<input aria-label={'Lots pour '+m.name} type="number" min="0.001" step="any" max={maxLots} value={selected[m.id]?.lots||'0.01'} onChange={e=>setSelected(s=>({...s,[m.id]:{...s[m.id],lots:e.target.value}}))}/></label></div>)}<label className="check"><input type="checkbox" checked={masterConsent} onChange={e=>setMasterConsent(e.target.checked)}/>Je confirme les stratégies et volumes sélectionnés, y compris les désabonnements.</label><button disabled={busy||!masterConsent||error} onClick={()=>void action({action:'masters',consent:masterConsent,masters:Object.entries(selected).filter(([,v])=>v.on).map(([id,v])=>({id,lots:Number(v.lots)}))})}>Enregistrer les stratégies</button></section><section><h2>Déconnecter le copieur</h2><p>Retire les abonnements et déconnecte ce compte. Ne supposez pas que les positions déjà ouvertes seront clôturées : vérifiez-les dans MetaTrader.</p><label className="check"><input type="checkbox" checked={disconnectConsent} onChange={e=>setDisconnectConsent(e.target.checked)}/>Je confirme la déconnexion de ce compte.</label><button disabled={busy||!disconnectConsent||error} onClick={()=>void action({action:'disconnect',consent:disconnectConsent})}>Déconnecter</button></section></>}
 <style jsx>{`.sth-page{max-width:1100px;margin:auto;color:#eee}.sth-page h1{font-size:34px;font-weight:650;margin:12px 0}.sth-page h2{font-size:20px;font-weight:600}.sth-page p{font-size:14px;line-height:1.6;margin:12px 0}.sth-page section{background:#111210;border:1px solid #ffc86735;border-radius:22px;padding:24px;margin-top:24px}.row,.master{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap}.fields{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:20px 0}label{display:flex;flex-direction:column;gap:8px;font-size:14px}.check{flex-direction:row;align-items:flex-start;margin:20px 0}.check input{width:20px;height:20px;min-height:20px;flex-shrink:0}input,select{background:#080908;border:1px solid #ffffff25;border-radius:10px;padding:10px;color:#fff;font-size:16px;min-height:44px;min-width:0}button{padding:12px 18px;border:1px solid #ffc86760;border-radius:10px;color:#ffc867;min-height:44px}button:disabled{opacity:.4;cursor:not-allowed}.muted{color:#aaa}.master{border-bottom:1px solid #ffffff15;padding:15px 0}.master>label:last-child{max-width:130px}@media(max-width:650px){.fields{grid-template-columns:1fr}.sth-page section{padding:16px}.sth-page h1{font-size:28px}}`}</style></main>;
}
